In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [4]:
l

[1, 2, 3, 4]

In [5]:
type(l)

list

In [6]:
a=np.array(l)

In [7]:
a

array([1, 2, 3, 4])

In [8]:
a1=np.array([[1,2,3],[4,5,6]])

In [10]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a1.dtype

dtype('int32')

In [12]:
a2=np.array([[[1,2,3],[4,5,6]]])

In [13]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
type(a1)

numpy.ndarray

In [15]:
type(a2)

numpy.ndarray

In [16]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [17]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
a3.ndim

3

In [19]:
l=[1,2,3,4]

In [23]:
a=np.asanyarray(l)

In [21]:
m=np.matrix(l)

In [22]:
m

matrix([[1, 2, 3, 4]])

In [24]:
a[0]=10

In [25]:
a

array([10,  2,  3,  4])